# Generated by Django 3.2.7 on 2021-10-27 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent41Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('web_address', models.URLField(blank=True, null=True, verbose_name='Web Address')),
                ('phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='customer service phone')),
                ('whatsapp', models.CharField(blank=True, max_length=15, null=True, verbose_name='whatsapp number')),
                ('email', models.EmailField(blank=True, max_length=15, null=True, verbose_name='Email')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
