# Generated by Django 3.2.7 on 2021-10-27 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0002_alter_agent41details_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent41Pricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.IntegerField(blank=True, null=True, verbose_name='Apartment Percentage')),
                ('commission', models.IntegerField(blank=True, null=True, verbose_name='Apartment Commission')),
                ('service_fee', models.BigIntegerField(blank=True, null=True, verbose_name='Apartment Percentage')),
            ],
        ),
        migrations.AddField(
            model_name='agent41details',
            name='address',
            field=models.CharField(blank=True, default='40 Golden palace sabo Auchi, edo state.', max_length=500, null=True, verbose_name='office Address'),
        ),
    ]
