# Generated by Django 3.2.7 on 2021-10-27 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0003_auto_20211027_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent41pricing',
            name='service_fee',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Service Fee'),
        ),
    ]
