# Generated by Django 3.2.7 on 2021-11-01 16:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Apartments', '0005_alter_commercialapartmentrequest_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Management', '0004_alter_agent41pricing_service_fee'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceFeePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.BigIntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('com_apartment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paid_for_comm', to='Apartments.commercialapartmentrequest')),
                ('res_apartment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paid_for_res', to='Apartments.residentialapartmentrequest')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paid_to', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AgentFeePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.BigIntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('com_apartment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paid_agent_comm', to='Apartments.commercialapartmentrequest')),
                ('res_apartment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paid_agent_res', to='Apartments.residentialapartmentrequest')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paid_to_Agent', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
