# Generated by Django 3.2.7 on 2021-11-01 16:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Management', '0005_agentfeepayment_servicefeepayment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agentfeepayment',
            old_name='staff',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='servicefeepayment',
            name='staff',
        ),
        migrations.AddField(
            model_name='servicefeepayment',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='staff_paid_to', to='auth.user'),
            preserve_default=False,
        ),
    ]
