# Generated by Django 3.2.7 on 2021-11-16 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0006_auto_20211101_1758'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentPaymentUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.IntegerField(default=100)),
                ('payment_threshold', models.BigIntegerField(default=1000)),
            ],
        ),
    ]
