# Generated by Django 3.2.7 on 2021-11-20 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0008_expenses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenses',
            name='purpose',
            field=models.TextField(max_length=1000),
        ),
    ]
