# Generated by Django 3.2.7 on 2021-11-24 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0010_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent41details',
            name='about',
            field=models.TextField(blank=True, default='about Agent41', null=True, verbose_name='About Agent41'),
        ),
        migrations.AddField(
            model_name='agent41details',
            name='agent_policy',
            field=models.TextField(blank=True, default='agent policy should be wrinting here.', null=True, verbose_name='agent policy'),
        ),
        migrations.AddField(
            model_name='agent41details',
            name='landlord_policy',
            field=models.TextField(blank=True, default='landlord policy should be wrinting here.', null=True, verbose_name='landlord policy'),
        ),
        migrations.AddField(
            model_name='agent41details',
            name='policy',
            field=models.TextField(blank=True, default='policy should be wrinting here.', null=True, verbose_name='policy'),
        ),
        migrations.AlterField(
            model_name='agent41pricing',
            name='commission',
            field=models.IntegerField(blank=True, null=True, verbose_name='Agent Commission'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='message',
            field=models.TextField(max_length=255),
        ),
    ]
