# Generated by Django 3.2.7 on 2021-10-26 07:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Apartments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commercialapartment',
            name='approved_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='comm_approved_by_user', to='auth.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='residentialapartment',
            name='approved_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='approved_by_user', to='auth.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='commercialapartment',
            name='landlord_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Landlord or CareTaker Name'),
        ),
        migrations.AlterField(
            model_name='commercialapartment',
            name='landlord_phone',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Landlord or CareTaker phone'),
        ),
        migrations.AlterField(
            model_name='residentialapartment',
            name='landlord_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Landlord or CareTaker Name'),
        ),
        migrations.AlterField(
            model_name='residentialapartment',
            name='landlord_phone',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Landlord or CareTaker phone'),
        ),
    ]
