# Generated by Django 3.2.7 on 2021-10-26 09:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Apartments', '0002_auto_20211026_0837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commercialapartment',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comm_approved_by_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='residentialapartment',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approved_by_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
