# Generated by Django 3.2.7 on 2021-10-26 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Apartments', '0003_auto_20211026_1058'),
    ]

    operations = [
        migrations.AddField(
            model_name='commercialapartment',
            name='care_taker',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='commercialapartment',
            name='landlord',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='residentialapartment',
            name='care_taker',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='residentialapartment',
            name='landlord',
            field=models.BooleanField(default=True),
        ),
    ]
