# Generated by Django 3.2.7 on 2021-10-26 17:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Apartments', '0004_auto_20211026_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commercialapartmentrequest',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='confirm_by_comm', to=settings.AUTH_USER_MODEL),
        ),
    ]
