# Generated by Django 3.2.7 on 2021-11-19 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Apartments', '0005_alter_commercialapartmentrequest_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='commercialapartmentrequest',
            name='agent_fee',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='commercialapartmentrequest',
            name='service_fee',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='residentialapartmentrequest',
            name='agent_fee',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='residentialapartmentrequest',
            name='service_fee',
            field=models.BooleanField(default=False),
        ),
    ]
