# Generated by Django 3.2.7 on 2021-11-16 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_Profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofiles',
            name='apartment',
            field=models.BigIntegerField(default=0),
        ),
    ]
