# Generated by Django 3.2.7 on 2021-11-16 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_Profiles', '0002_userprofiles_apartment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofiles',
            name='apartment',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
    ]
